image: Visual Studio 2019 Preview
install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
build_script:
  - nuget restore -Verbosity quiet -PackagesDirectory .\packages
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /p:SolutionDir=.\
after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery